
export const countyToRegion: { [key: string]: string } = {
    "Kiambu": "Central Highlands",
    "Murang'a": "Central Highlands",
    "Nyeri": "Central Highlands",
    "Kirinyaga": "Central Highlands",
    "Nyandarua": "Central Highlands",
    "Nakuru": "Rift Valley",
    "Baringo": "Rift Valley",
    "Laikipia": "Rift Valley",
    "Narok": "Rift Valley",
    "Kajiado": "Rift Valley",
    "Kericho": "Rift Valley",
    "Bomet": "Rift Valley",
    "Uasin Gishu": "Rift Valley",
    "Elgeyo-Marakwet": "Rift Valley",
    "Nandi": "Rift Valley",
    "Trans Nzoia": "Rift Valley",
    "West Pokot": "Rift Valley",
    "Turkana": "Rift Valley",
    "Kakamega": "Western Region",
    "Vihiga": "Western Region",
    "Bungoma": "Western Region",
    "Busia": "Western Region",
    "Kisumu": "Nyanza Region",
    "Siaya": "Nyanza Region",
    "Homa Bay": "Nyanza Region",
    "Migori": "Nyanza Region",
    "Kisii": "Nyanza Region",
    "Nyamira": "Nyanza Region",
    "Meru": "Eastern Region",
    "Tharaka-Nithi": "Eastern Region",
    "Embu": "Eastern Region",
    "Machakos": "Eastern Region",
    "Makueni": "Eastern Region",
    "Kitui": "Eastern Region",
    "Mombasa": "Coast Region",
    "Kwale": "Coast Region",
    "Kilifi": "Coast Region",
    "Tana River": "Coast Region",
    "Lamu": "Coast Region",
    "Taita-Taveta": "Coast Region",
    "Garissa": "North Eastern Region",
    "Wajir": "North Eastern Region",
    "Mandera": "North Eastern Region",
    "Marsabit": "North Eastern Region",
    "Isiolo": "North Eastern Region",
    "Samburu": "North Eastern Region"
  };


export const counties = Object.keys(countyToRegion);